basePath: /v1
definitions:
  DTOs.CreateTemplateDTO:
    properties:
      name:
        type: string
    required:
    - name
    type: object
host: localhost:9500
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Template API
  version: "1.0"
paths:
  /api/templates/:
    post:
      consumes:
      - application/json
      operationId: create-template-id
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/DTOs.CreateTemplateDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: int
      summary: Add a new item to the template list
      tags:
      - root
  /api/templates/{id}:
    get:
      consumes:
      - application/json
      operationId: get-template-by-id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ReadTemplateDTO
      summary: get a template by ID
      tags:
      - root
schemes:
- http
swagger: "2.0"
